# public/admin/config.yml

# This tells the CMS to use the GitHub backend
backend:
  name: github
  repo: muhammadawa242/launchcore
  branch: main # Or master, whichever is your main branch
  auth_endpoint: auth

# This tells the CMS where to store images
media_folder: "public/uploads" # Where to upload the media
public_folder: "/uploads" # The src attribute for the media

collections:
  - name: "pages"
    label: "Page Content"
    files:
      - name: "about"
        label: "About Section"
        file: "src/content/about.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Paragraph", name: "paragraph", widget: "markdown" }
          - { label: "Button Text", name: "buttonText", widget: "string" }
          - { label: "Button Link", name: "buttonLink", widget: "string" }

  - name: "testimonials"
    label: "Testimonials"
    file: "src/content/testimonials.json"
    fields:
      - name: items
        label: Testimonials
        label_singular: Testimonial
        widget: list
        identifier_field: author # <-- ADD THIS LINE
        fields:
          - { label: "Quote", name: "quote", widget: "text" }
          - { label: "Author", name: "author", widget: "string" }
